require "colortouch.Node"
require "colortouch.Container"
require "colortouch.Button"
require "colortouch.SwitchButton"
require "colortouch.Label"
require "colortouch.HTMLLabel"
require "colortouch.Spacer"
require "colortouch.layout"
require "colortouch.ImageView"
require "colortouch.ScrollView"
require "colortouch.EventProp"
require "colortouch.MenuProp"

require "colortouch/pickerview/PickerViewDataSource"
require "colortouch/pickerview/PickerView"
require "colortouch/pickerview/DatePicker"
require "colortouch/pickerview/MultipleSelectedView"
require "colortouch/input/DateInput"
require "colortouch/input/SelectInput"
require "colortouch/input/EditText"
require "colortouch/input/TextField"
require "colortouch/dialog/ModalDialog"
require "colortouch/dialog/IToast"
require "colortouch/dialog/AlertView"
require "colortouch/dialog/ActionSheet"
require "colortouch/vedioplay/VedioPlayView"
require "colortouch/tableview/TableView"
require "colortouch/tableview/TableViewDataSource"
require "colortouch/webview/WebView"
require "colortouch/input/QRView"
require "colortouch/viewpager/ViewPager"
require "colortouch/viewpager/ViewPagerAdapter"
require "colortouch/viewpager/PageIndicator"
require "colortouch/viewpager/IndicatorViewPager"
require "colortouch/ThrowView"
if platform.isIOS() then
require "colortouch/media/VLCPlayer"
require "colortouch.TabbarView"
require "colortouch.version"
else
require "colortouch.HorizontalScrollView"
require "colortouch/viewpager/ViewPager"
require "colortouch/dialog/ActionSheet"
end
Property = EventProp.Property